// Ampere task impls
#include "tasks/ampere/embedding.cuh"
#include "tasks/ampere/silu_mul.cuh"
// Hopper task impls
#include "tasks/cute/hopper/gemm_ws.cuh"
#include "tasks/cute/hopper/gemm_ws_cooperative.cuh"
#include "tasks/cute/hopper/gemm_ws_mpk.cuh"
#include "tasks/hopper/linear_hopper.cuh"
#include "tasks/hopper/linear_swapAB_hopper.cuh"
#include "tasks/hopper/multitoken_paged_attention_hopper.cuh"
#include "tasks/hopper/rmsnorm_hopper.cuh"
#include "tasks/hopper/silu_mul_hopper.cuh"
// Blackwell task impls
#include "argmax_sm100.cuh"
#include "attention_sm100.cuh"
#include "fp8_group_gemm_sm100.cuh"
#include "linear_fp8_1d2d_sm100.cuh"
#include "linear_sm100_mpk.cuh"
#include "mla_kv_cache_gather_sm100.cuh"
#include "mla_dispatch_sm100.cuh"
// TODO: Enable when MLA MTP codegen is wired up
// #include "mla_mtp_decode_sm100.cuh"
#include "mla_prefill_sm100.cuh"
#include "mla_reduce_sm100.cuh"
// #include "mla_sm100_2sm.cuh"
// #include "sm100_ptx.cuh"
#include "moe_linear_sm100.cuh"
#include "mul_sum_add_sm100.cuh"
#include "per_token_group_quantize_fp8.cuh"
#include "tensor_init.cuh"
#include "topk_sigmoid_sm100.cuh"
#include "topk_softmax_sm100.cuh"
// TODO: Speculative decoding / MTP tasks (include paths need fixing for mpk-exp)
// #include "tasks/speculative_decoding/target_verify.cuh"
// #include "tasks/speculative_decoding/target_verify_mtp.cuh"
// #include "tasks/speculative_decoding/prompt_lookup.cuh"
// #include "tasks/speculative_decoding/mtp_token_ops.cuh"
// #include "tasks/common/sampling.cuh"
